/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var Cur_reserved_slot = ""
				var Delay = 30000
				var DelayLong = 30000L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						forward("send_home", "send_home(X)" ,"cargorobot" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("disengaged") { //this:State
					action { //it:State
						CommUtils.outgreen("cargoservice | DISENGAGED: waiting for cargo load request")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="evaluate_request",cond=whenRequest("load_request"))
					transition(edgeName="t01",targetState="outOfService",cond=whenDispatch("sensorError"))
					transition(edgeName="t02",targetState="set_delay",cond=whenDispatch("setDelay"))
				}	 
				state("set_delay") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("setDelay(X)"), Term.createTerm("setDelay(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Delay = payloadArg(0).toInt()
								    			DelayLong = Delay.toLong() 
						}
						CommUtils.outblue("cargoservice | setting delay for testing: $Delay ms")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("evaluate_request") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | checking with hold if a slot is available")
						request("reserve_slot", "reserve_slot(X)" ,"holdservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="check_ioport",cond=whenReply("reserve_ok"))
					transition(edgeName="t04",targetState="load_rejected",cond=whenReply("reserve_fail"))
					transition(edgeName="t05",targetState="outOfService",cond=whenDispatch("sensorError"))
				}	 
				state("load_rejected") { //this:State
					action { //it:State
						 
									val Error = "No slots available, load is rejected."
						CommUtils.outred("cargoservice | $Error")
						answer("load_request", "load_rejected", "load_rejected($Error)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkloadqueue", cond=doswitch() )
				}	 
				state("check_ioport") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("reserve_ok(N)"), Term.createTerm("reserve_ok(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												Cur_reserved_slot = payloadArg(0)
								CommUtils.outblack("cargoservice | Reserved slot: $Cur_reserved_slot")
						}
						request("is_cargo_present", "is_cargo_present(X)" ,"sensorservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="retry_later",cond=whenReply("cargo_present"))
					transition(edgeName="t07",targetState="send_accept",cond=whenReply("cargo_absent"))
					transition(edgeName="t08",targetState="outOfService",cond=whenDispatch("sensorError"))
				}	 
				state("retry_later") { //this:State
					action { //it:State
						 
									val Error = "IOPort is already occupied by a cargo, retry later."
						CommUtils.outred("cargoservice | $Error")
						answer("load_request", "retrylater", "retrylater($Error)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkloadqueue", cond=doswitch() )
				}	 
				state("send_accept") { //this:State
					action { //it:State
						answer("load_request", "load_accepted", "load_accepted(X)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitforcargo", cond=doswitch() )
				}	 
				state("waitforcargo") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | PLACE CARGO AT IOPORT")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_waitforcargo", 
				 	 					  scope, context!!, "local_tout_"+name+"_waitforcargo", DelayLong )  //OCT2023
					}	 	 
					 transition(edgeName="t09",targetState="cargo_timeout",cond=whenTimeout("local_tout_"+name+"_waitforcargo"))   
					transition(edgeName="t010",targetState="engaged",cond=whenDispatch("container_in"))
					transition(edgeName="t011",targetState="outOfService",cond=whenDispatch("sensorError"))
				}	 
				state("cargo_timeout") { //this:State
					action { //it:State
						 
									val Error = "No cargo has arrived in IOPort, timeout."
						CommUtils.outred("cargoservice | $Error")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkloadqueue", cond=doswitch() )
				}	 
				state("engaged") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | System engaged, load operation is being handled by cargorobot")
						request("handle_cargo_load", "handle_cargo_load($Cur_reserved_slot)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="checkloadqueue",cond=whenReply("cargo_load_success"))
					transition(edgeName="t013",targetState="disengaged",cond=whenReply("cargo_load_failed"))
					transition(edgeName="t014",targetState="outOfService",cond=whenDispatch("sensorError"))
				}	 
				state("checkloadqueue") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_checkloadqueue", 
				 	 					  scope, context!!, "local_tout_"+name+"_checkloadqueue", 10.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t015",targetState="s0",cond=whenTimeout("local_tout_"+name+"_checkloadqueue"))   
					transition(edgeName="t016",targetState="evaluate_request",cond=whenRequest("load_request"))
				}	 
				state("outOfService") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | sensor error: OUT OF SERVICE!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t017",targetState="reply_oos",cond=whenRequest("load_request"))
					transition(edgeName="t018",targetState="s0",cond=whenDispatch("sensorOK"))
				}	 
				state("reply_oos") { //this:State
					action { //it:State
						answer("load_request", "retrylater", "retrylater(X)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="outOfService", cond=doswitch() )
				}	 
			}
		}
} 
