/* Generated by AN DISI Unibo */ 
package it.unibo.sensorservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sensorservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				val DFREE = 100
				var container_present = false
				var out_of_service = false
				var oos_counter = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_for_data", cond=doswitch() )
				}	 
				state("wait_for_data") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handle_request",cond=whenRequest("is_cargo_present"))
					transition(edgeName="t01",targetState="processdata",cond=whenEvent("sonardata"))
				}	 
				state("handle_request") { //this:State
					action { //it:State
						if(  container_present  
						 ){answer("is_cargo_present", "cargo_present", "cargo_present(X)"   )  
						}
						else
						 {answer("is_cargo_present", "cargo_absent", "cargo_absent(X)"   )  
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_for_data", cond=doswitch() )
				}	 
				state("processdata") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonardata(D)"), Term.createTerm("sonardata(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Distance = payloadArg(0).toInt()  
								CommUtils.outgreen("sensorservice | Distance = $Distance")
								if(  Distance > DFREE  
								 ){ oos_counter += 1  
								if(  oos_counter >= 2 && !out_of_service  
								 ){ out_of_service = true  
								forward("sensorError", "sensorError(X)" ,"cargoservice" ) 
								}
								}
								else
								 { oos_counter = 0  
								 if(  out_of_service  
								  ){ out_of_service = false  
								 forward("sensorOK", "sensorOK(X)" ,"cargoservice" ) 
								 }
								 }
								if(  !out_of_service  
								 ){if(  Distance < DFREE/2  
								 ){if(  !container_present  
								 ){ container_present = true  
								emit("container_in", "container_in(X)" ) 
								}
								}
								else
								 { container_present = false  
								 }
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_for_data", cond=doswitch() )
				}	 
			}
		}
} 
