/* Generated by AN DISI Unibo */ 
package it.unibo.holdstatusservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Holdstatusservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						connectToMqttBroker( "tcp://localhost:1883" )
						subscribe(  "holdstatusrequest" ) //mqtt.subscribe(this,topic)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_for_request", cond=doswitch() )
				}	 
				state("wait_for_request") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="send_status_request",cond=whenEvent("hold_status_request"))
				}	 
				state("send_status_request") { //this:State
					action { //it:State
						request("get_hold_status", "get_hold_status(X)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="update_hold_status",cond=whenReply("hold_status"))
				}	 
				state("update_hold_status") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("hold_status(STATUS)"), Term.createTerm("hold_status(S)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val Message = payloadArg(0) 
								//val m = MsgUtil.buildEvent(name, "display_web", "display_web($Message)" ) 
								publish(MsgUtil.buildEvent(name,"display_web","display_web($Message)").toString(), "display" )   
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_for_request", cond=doswitch() )
				}	 
			}
		}
} 
