/* Generated by AN DISI Unibo */ 
package it.unibo.holdservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Holdservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var hold = Hold(4)
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t031",targetState="look_for_empty_slot",cond=whenRequest("reserve_slot"))
					transition(edgeName="t032",targetState="free_slot_state",cond=whenDispatch("free_slot"))
					transition(edgeName="t033",targetState="send_hold_status",cond=whenRequest("get_hold_status"))
				}	 
				state("look_for_empty_slot") { //this:State
					action { //it:State
						
									val slotsOccupation = hold.getSlotsOccupation()
									var EmptySlot = "no"
									 
									for ((i,occupation) in slotsOccupation.withIndex()) {
						    			if(!occupation){
						    				EmptySlot = "slot"+(i+1)
						    				hold.occupySlot(i+1)
						    				break
						    			}
									}
						if(  !EmptySlot.equals("no")  
						 ){answer("reserve_slot", "reserve_ok", "reserve_ok($EmptySlot)"   )  
						}
						else
						 {answer("reserve_slot", "reserve_fail", "reserve_fail(X)"   )  
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
				state("free_slot_state") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("free_slot(SLOT)"), Term.createTerm("free_slot(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								        		val slotId = payloadArg(0).substringAfter("slot").toInt()
								            	hold.freeSlot(slotId)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
				state("send_hold_status") { //this:State
					action { //it:State
						
									val hold_status = hold.getSlotsOccupation()
									var Msg = ""
									
									for (occupation in hold_status) {
									    Msg += if (occupation) "1" else "0"
									}
						answer("get_hold_status", "hold_status", "hold_status($Msg)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
} 
