/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				// stato
				val Step = 335
				
				// (y,x)
				val positions = hashMapOf(
					"home"    	to arrayOf(0, 0),
					"io_port" 	to arrayOf(4, 0),
				    "slot1"   	to arrayOf(1, 1),
				    "slot2" 	to arrayOf(1, 4),
				    "slot3" 	to arrayOf(3, 1),
				    "slot4" 	to arrayOf(3, 4),
				    "slot5" 	to arrayOf(2, 5)
				)
				
				val directions = hashMapOf(
					"home"    	to "down",
					"io_port" 	to "down",
				    "slot1"   	to "right",
				    "slot2" 	to "left",
				    "slot3" 	to "right",
				    "slot4" 	to "left",
				    "slot5" 	to "left"
				)
				
				var Destination = ""
				var Target_slot = ""
				
				var X = 0
				var Y = 0
				
				var cur_coordinates = IntArray(2)
				var cur_direction = ""
				var input_cur_pos = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("cargorobot | waiting for cargo load request")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t019",targetState="goto_ioport",cond=whenRequest("handle_cargo_load"))
					transition(edgeName="t020",targetState="goto_home",cond=whenDispatch("send_home"))
				}	 
				state("goto_ioport") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("handle_cargo_load(TARGET_SLOT)"), Term.createTerm("handle_cargo_load(TARGET_SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												Target_slot = payloadArg(0)
						}
						
									Destination = "io_port"
									val coords = positions[Destination]!!
									X = coords[0]
									Y = coords[1]
						request("moverobot", "moverobot($X,$Y,$Step)" ,"robotsmart" )  
						CommUtils.outgreen("cargorobot | moving towards io_port...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t021",targetState="goto_slot5",cond=whenReply("moverobotdone"))
					transition(edgeName="t022",targetState="handle_move_error",cond=whenReply("moverobotfailed"))
				}	 
				state("handle_move_error") { //this:State
					action { //it:State
						CommUtils.outred("cargorobot | move error, could not complete cargo load")
						answer("handle_cargo_load", "cargo_load_failed", "cargo_load_failed(X)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("goto_slot5") { //this:State
					action { //it:State
						delay(3000) 
						CommUtils.outgreen("cargorobot | moving towards slot5...")
						
									Destination = "slot5"
									val coords = positions[Destination]!!
									X = coords[0]
									Y = coords[1]
						request("moverobot", "moverobot($X,$Y,$Step)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t023",targetState="goto_target_slot",cond=whenReply("moverobotdone"))
					transition(edgeName="t024",targetState="handle_move_error",cond=whenReply("moverobotfailed"))
				}	 
				state("arrived_at_slot5") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | arrived at slot 5")
						 
									val Direction = directions[Destination]!!
						CommUtils.outmagenta("$name | turning $Direction ...")
						forward("setrobotstate", "setpos($X,$Y,$Direction)" ,"robotsmart" ) 
						delay(5000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="goto_target_slot", cond=doswitch() )
				}	 
				state("goto_target_slot") { //this:State
					action { //it:State
						delay(2000) 
						CommUtils.outgreen("cargorobot | moving towards $Target_slot...")
						
									val coords = positions[Target_slot]!!
									X = coords[0]
									Y = coords[1]
						request("moverobot", "moverobot($X,$Y,$Step)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t025",targetState="cargo_load_done",cond=whenReply("moverobotdone"))
					transition(edgeName="t026",targetState="handle_move_error",cond=whenReply("moverobotfailed"))
				}	 
				state("arrived_at_target_slot") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | arrived at target slot")
						 
									val Direction = directions[Target_slot]!!
						forward("setrobotstate", "setpos($X,$Y,$Direction)" ,"robotsmart" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="cargo_load_done", cond=doswitch() )
				}	 
				state("goto_home") { //this:State
					action { //it:State
						request("getrobotstate", "getrobotstate(ARG)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t027",targetState="evaluate_home",cond=whenReply("robotstate"))
				}	 
				state("evaluate_home") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("robotstate(POS,DIR)"), Term.createTerm("robotstate(POS,D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												input_cur_pos = payloadArg(0)
												val inner = input_cur_pos.substringAfter("(").substringBefore(")")
												val parts = inner.split(",")
												
												val x = parts[0].trim().toInt()
												val y = parts[1].trim().toInt()
												
												cur_coordinates[0] = x
												cur_coordinates[1] = y
												cur_direction = payloadArg(1)
						}
						
									Destination = "home"
									val coords = positions[Destination]!!
									X = coords[0]
									Y = coords[1]
						CommUtils.outyellow("cargorobot | cheking if already home, currently in position $X , $Y , msg: $input_cur_pos, cur: ${cur_coordinates[0]} , ${cur_coordinates[1]}")
						if(  X != cur_coordinates[0] && Y != cur_coordinates[1]  
						 ){CommUtils.outgreen("cargorobot | moving towards home...")
						request("moverobot", "moverobot($X,$Y,$Step)" ,"robotsmart" )  
						}
						else
						 {forward("already_home", "already_home(X)" ,name ) 
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t028",targetState="s0",cond=whenReply("moverobotdone"))
					transition(edgeName="t029",targetState="handle_move_error",cond=whenReply("moverobotfailed"))
					transition(edgeName="t030",targetState="s0",cond=whenDispatch("already_home"))
				}	 
				state("arrived_at_home") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargorobot | arrived at home")
						 
									val Direction = directions[Destination]!!
						forward("setrobotstate", "setpos($X,$Y,$Direction)" ,"robotsmart" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t031",targetState="s0",cond=whenReply("setdirectiondone"))
				}	 
				state("cargo_load_done") { //this:State
					action { //it:State
						delay(2000) 
						answer("handle_cargo_load", "cargo_load_success", "cargo_load_success(X)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
} 
