/* Generated by AN DISI Unibo */ 
package it.unibo.ioservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Ioservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var Message = ""
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						connectToMqttBroker( "tcp://localhost:1883" )
						subscribe(  "pushbutton" ) //mqtt.subscribe(this,topic)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_for_push", cond=doswitch() )
				}	 
				state("wait_for_push") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="send_push",cond=whenEvent("push"))
				}	 
				state("send_push") { //this:State
					action { //it:State
						request("load_request", "load_request(X)" ,"cargoservice" )  
						Message = "button pressed, load request sent" 
						emitlocal("display", "display(Message)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="accept",cond=whenReply("load_accepted"))
					transition(edgeName="t02",targetState="reject",cond=whenReply("load_rejected"))
					transition(edgeName="t03",targetState="retry",cond=whenReply("retrylater"))
				}	 
				state("accept") { //this:State
					action { //it:State
						 val Message = "load accepted" 
						//val m = MsgUtil.buildEvent(name, "display_web", "display_web($Message)" ) 
						publish(MsgUtil.buildEvent(name,"display_web","display_web($Message)").toString(), "display" )   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_for_push", cond=doswitch() )
				}	 
				state("reject") { //this:State
					action { //it:State
						 val Message = "load rejected" 
						//val m = MsgUtil.buildEvent(name, "display_web", "display_web($Message)" ) 
						publish(MsgUtil.buildEvent(name,"display_web","display_web($Message)").toString(), "display" )   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_for_push", cond=doswitch() )
				}	 
				state("retry") { //this:State
					action { //it:State
						 val Message = "retry later" 
						//val m = MsgUtil.buildEvent(name, "display_web", "display_web($Message)" ) 
						publish(MsgUtil.buildEvent(name,"display_web","display_web($Message)").toString(), "display" )   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_for_push", cond=doswitch() )
				}	 
			}
		}
} 
