/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("disengaged") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="outOfService",cond=whenDispatch("sensorError"))
					transition(edgeName="t01",targetState="handleLoadRequest",cond=whenRequest("load_request"))
				}	 
				state("handleLoadRequest") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkIoport", cond=doswitch() )
				}	 
				state("checkIoport") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="startLoading",cond=whenReply("container_present"))
					transition(edgeName="t03",targetState="waitContainer",cond=whenReply("container_absent"))
				}	 
				state("waitContainer") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="startLoading",cond=whenDispatch("containerIn"))
				}	 
				state("startLoading") { //this:State
					action { //it:State
						request("do_move", "do_move(ioport)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="moveToSlot",cond=whenReply("move_done"))
					transition(edgeName="t06",targetState="handleMoveFailed",cond=whenReply("move_failed"))
				}	 
				state("moveToSlot") { //this:State
					action { //it:State
						request("do_move", "do_move($SLOT)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="loadComplete",cond=whenReply("move_done"))
					transition(edgeName="t08",targetState="handleMoveFailed",cond=whenReply("move_failed"))
				}	 
				state("loadComplete") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("handleMoveFailed") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("outOfService") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="recoveryFromOOS",cond=whenDispatch("sensorReady"))
					transition(edgeName="t010",targetState="rejectOOS",cond=whenRequest("load_request"))
				}	 
				state("rejectOOS") { //this:State
					action { //it:State
						answer("load_request", "retrylater", "retrylater(out_of_service)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="outOfService", cond=doswitch() )
				}	 
				state("recoveryFromOOS") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
			}
		}
} 
