/* Generated by AN DISI Unibo */ 
package it.unibo.displayservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Displayservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var Msg = ""  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						connectToMqttBroker( "tcp://localhost:1883" )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_for_display_event", cond=doswitch() )
				}	 
				state("wait_for_display_event") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="display_message",cond=whenEvent("display"))
				}	 
				state("display_message") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("display(MESSAGE)"), Term.createTerm("display(M)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Msg = payloadArg(0) 
								CommUtils.outgreen("display | message: $Msg")
								//val m = MsgUtil.buildEvent(name, "display_web", "display_web($Msg)" ) 
								publish(MsgUtil.buildEvent(name,"display_web","display_web($Msg)").toString(), "display" )   
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait_for_display_event", cond=doswitch() )
				}	 
			}
		}
} 
