/* Generated by AN DISI Unibo */ 
package it.unibo.holdservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Holdservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var hold = Hold(4)
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t030",targetState="look_for_empty_slot",cond=whenRequest("reserve_slot"))
					transition(edgeName="t031",targetState="set_full",cond=whenDispatch("test_hold_full"))
					transition(edgeName="t032",targetState="set_empty",cond=whenDispatch("test_hold_empty"))
				}	 
				state("look_for_empty_slot") { //this:State
					action { //it:State
						
									val slotsOccupation = hold.getSlotsOccupation()
									var EmptySlot = "no"
									
									for ((i,occupation) in slotsOccupation.withIndex()) {
						    			if(!occupation){
						    				EmptySlot = "slot"+(i+1)
						    				hold.occupySlot(i+1)
						    				break
						    			}
									}
									
						if(  !EmptySlot.equals("no")  
						 ){answer("reserve_slot", "reserve_ok", "reserve_ok($EmptySlot)"   )  
						}
						else
						 {answer("reserve_slot", "reserve_fail", "reserve_fail(X)"   )  
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
				state("set_full") { //this:State
					action { //it:State
						CommUtils.outblue("hold | test mode: set hold to full")
							hold.occupySlot(1)
									hold.occupySlot(2)
									hold.occupySlot(3)
									hold.occupySlot(4)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
				state("set_empty") { //this:State
					action { //it:State
						CommUtils.outblue("hold | test mode: set hold to empty")
							hold.freeSlot(1)
									hold.freeSlot(2)
									hold.freeSlot(3)
									hold.freeSlot(4)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
} 
