/* Generated by AN DISI Unibo */ 
package it.unibo.hold_controller

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Hold_controller ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var hold = new Hold(4)
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("hold_controller | working.....")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t021",targetState="look_for_empty_slot",cond=whenRequest("reserve_slot"))
				}	 
				state("look_for_empty_slot") { //this:State
					action { //it:State
						
									val slotsOccupation = hold.getSlotsOccupation()
									var emptySlot = "no"
									
									for ((i,occupation) in slotsOccupation.withIndex()) {
						    			if(!occupation){
						    				emptySlot = "slot"+(i+1)
						    				hold.occupySlot(i)
						    				break
						    			}
									}
									
						if(  !emptySlot.equals("no")  
						 ){answer("reserve_slot", "reserve_ok", "reserve_ok(emptySlot)"   )  
						}
						else
						 {answer("reserve_slot", "reserve_fail", "reserve_fail(X)"   )  
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
} 
