/* Generated by AN DISI Unibo */ 
package it.unibo.mock_pusbutton

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Mock_pusbutton ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						subscribe(  "push" ) //mqtt.subscribe(this,topic)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="send_load_request",cond=whenEvent("push"))
					transition(edgeName="t05",targetState="work",cond=whenReply("load_accepted"))
					transition(edgeName="t06",targetState="work",cond=whenReply("load_rejected"))
					transition(edgeName="t07",targetState="work",cond=whenReply("retrylater"))
				}	 
				state("send_load_request") { //this:State
					action { //it:State
						CommUtils.outblack("mock_pushbutton | sent load_request")
						request("load_request", "load_request(X)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="send_load_request",cond=whenEvent("push"))
					transition(edgeName="t09",targetState="work",cond=whenReply("load_accepted"))
					transition(edgeName="t010",targetState="work",cond=whenReply("load_rejected"))
					transition(edgeName="t011",targetState="work",cond=whenReply("retrylater"))
				}	 
			}
		}
} 
